### ISSUE TITLE
Markdown Compatibility Request

### ISSUE THREAD

**Issue by darkflameq** [wysiwygjs/wysiwyg.js#1]
Any chance of this happening?

I've gone through so many vanilla javascript wysiwygs and yours is my favorite implementation by far, just a shame it doesn't support Markdown.

**Comment by DaveM2011** [comment]
I am also interested in this feature although some fetaures of @wysiwygjs would ethier not work for example background color or the need to expand markdown to enable it

**Comment by wysiwygjs** [comment]
Sorry, this is only a "What You See Is What You Get" editor.
There is no support for Markdown/BBCode/...
