### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by Especially** [wysiwygjs/wysiwyg.js#12]
Not sure what I'm doing wrong,, I'm using a div contenteditable instead of a textarea, however that doesn't seem to be the problem, do I need to elaborate more? 
I'm using the latest version of Chrome by the way

**Comment by 1moere1** [comment]
same problem here.

**Comment by wysiwygjs** [comment]
Do you use the "raw" editor?
wysiwyg({element:<id>});

**Comment by Especially** [comment]
@1moere1 declare the div id or class in entire script that is stationary to your webpage. Search for the word

**Comment by Especially** [comment]
@1moere1 look for "// Raw Editor" on the index page and declare the div class or id (or text area class/Id) where it says #editor0

**Comment by wysiwygjs** [comment]
Typo in the docs: "getElmentById()" instead of "getElementById()"
Changed: You can also pass an id instead.

**Comment by 1moere1** [comment]
thanks @Especially and @wysiwygjs the problem was solved with the Raw Editor part ;)
