### ISSUE TITLE
IE8: link popover does not appears on link-element click

### ISSUE THREAD

**Issue by mreugen** [wysiwygjs/wysiwyg.js#13]
Hello! Great code you've written.
I've found following bug:

Test environment: VM Windows XP
Browser: IE8
Description: If you click on link-element in all other browsers you will get a popover where you can edit href attribute. In IE8 this popover appears not. Can you fix this issue please?

with best regards
Eugen

**Comment by wysiwygjs** [comment]
Fixed by 37fbdf7821

**Comment by mreugen** [comment]
tested, everything is great, thx
