### ISSUE TITLE
IE8/IE9: strange behavior for blockquote/(un)ordered list

### ISSUE THREAD

**Issue by mreugen** [wysiwygjs/wysiwyg.js#14]
I've found another bug:

Test environment: VM Windows XP
Browser: IE8/IE9
Condition: you have some text already in the content(with line breaks)
Description: if I try to select one line of the content and then press on blockquote/(un)ordered list => the whole text I have will stay in the selected element.

with best regards
Eugen

**Comment by wysiwygjs** [comment]
Sorry - didn't get the point. Could you explain in German?

**Comment by mreugen** [comment]
Hallo!
Beschreibung: Wenn bereits ein Text innen drin steht(mit Umbrüchen), und man versucht in IE8 oder IE9 eine Zeile zu selektieren und dann klickt auf z.B. "Liste" dann steht der kompletter Text in diesem Fall mit unter "1. " obwohl man nur eine Zeile selektiert hat. Das gleiche Verhalten auch beim Einrücken. Ich hoffe meine Erklärung jetzt war verständlicher. :) Mit freundlichen Grüßen, Eugen

**Comment by wysiwygjs** [comment]
Verstehe. "execCommand()" ist so voller Fehler.

**Comment by mreugen** [comment]
Habe heute festgestellt dass das Verhalten leider bei jedem IE auf(8-11) auftritt. :(
Vllt schau ich mir dein Code an(wenn ich eine Lösung finde dann poste ich sie hier).

Grüße
