### ISSUE TITLE
Current bower.json doesn't work with rails-assets.org

### ISSUE THREAD

**Issue by ProGM** [wysiwygjs/wysiwyg.js#19]
I think that's because the bower.json should be like this:

```json
{
  "name": "wysiwyg.js",
  "version": "1.0.0",
  "description": "wysiwyg contenteditable editor (lightweight + cross browser)",
  "homepage": "http://wysiwygjs.github.io/",
  "keywords": [
...
```

**Comment by wysiwygjs** [comment]
Changed "version".
Could you test if it works (we don't use bower)

**Comment by ProGM** [comment]
http://bower.io/search/?q=wysiwyg.js

It ways `updated two days ago`... Did you updated online bower? Or it's just cache?
