### ISSUE TITLE
Feature request - paste as plain text

### ISSUE THREAD

**Issue by gdanx** [wysiwygjs/wysiwyg.js#21]
Thank you for wysiwyg.js!
It would be nice to have an option to paste text as plain text into the editor.

**Comment by dandv** [comment]
@gdanx , can you please rename your issue to something more specific?

**Comment by gdanx** [comment]
done :)

**Comment by heather27stars** [comment]
Hi - just to add a please to this feature request. Really like wysiwyg.js, and this would be a great addition :)

**Comment by hoetz** [comment]
I'd have use for that as well :)

**Comment by muffe** [comment]
+1
