### ISSUE TITLE
break line , different behaviour in different brawsers

### ISSUE THREAD

**Issue by kozilla** [wysiwygjs/wysiwyg.js#22]
Hi,

Thanks for a nice tool. I have noticed that each browser encode break line differently. For example IE threats each line as <p> , chrom puts each line in separate div (except first line :( ) and firefox create br tag.

I am parsing html content of WYSIWYG editor to PDF format , how ever its a big headache because of not consistent text formatting. Is it any chance to have the same   output regardless which browser is in use ?

for example using  function wysiwyg.getHTML() for sample text formated as below  :

test
test
test

we have :
in firefox :

test<.br>test<.br>test<.br>

in chrome :
test<.div>test</.div><.div>test</.div>

in IE

<.p>test</.p><.p>test<./p><.p>test<.p/>

thanks for advance,

**Comment by jbhamilton** [comment]
Any response on this?

**Comment by medBouzid** [comment]
@jbhamilton @kozilla this behavior is an issue for a long time, unfortunately there is no way to deal with the inconsistency of browsers when it comes to content-editing.

**Comment by medBouzid** [comment]
+1 for this. It would be useful if there is a way to unify the way the enter key is handled, an option for <br> tag when hit enter, and another option for <p> when hit enter! or at least one of them which work cross browsers.
