### ISSUE TITLE
.html vs. .php

### ISSUE THREAD

**Issue by akuisma** [wysiwygjs/wysiwyg.js#23]
If I try to use this script inside .php file, nothing happens (ex. I rename the demo file index.html to index.php). I have Linux/Apache/Php and the other .php files are working proberly.

**Comment by wysiwygjs** [comment]
````PHP Parse error:  syntax error, unexpected '*' in /var/customers/webs/doppelbauer/wysiwyg.js/index.php on line 402````

Remove the PHP example code from from the onImageUpload() function.
