### ISSUE TITLE
publish wysiwyg.js on npm

### ISSUE THREAD

**Issue by Nyalab** [wysiwygjs/wysiwyg.js#24]
Hi,

I would like to use your editor on my project, but you have not published it on npm. Can you do it please ?

Thanks in advance

**Comment by wysiwygjs** [comment]
We don't use npm. What has to be done?

**Comment by kud** [comment]
I'm sorry for my newbie question but what is npm?

**Comment by Nyalab** [comment]
hi, thanks for your time.

you juste have to do a `npm publish` [tutorial here](https://docs.npmjs.com/getting-started/publishing-npm-packages)

if you don't have a npm user, you should create one before (it really is simple)

then you will have to have a proper `package.json`, you need to set your version number at `1.0.0` and not just `1`

let me know if you need any help

**Comment by wysiwygjs** [comment]
Merged the pull requests. Could you publish this account?
If you need write access to this repository please let me know.

**Comment by sergiors** [comment]
:+1:

**Comment by Nyalab** [comment]
hi, sorry for the delay, i was out of time. if you want, i can do it, i will need access to the repository yes, to publish git tags in order to publish on npm, if you want.

**Comment by wysiwygjs** [comment]
@Nyalab 
I have added you as "collaborator". Hope this helps.

**Comment by Nyalab** [comment]
yes thanks, it is done! your editor is [on npm](https://www.npmjs.com/package/wysiwyg.js), congrats!

**Comment by wysiwygjs** [comment]
Thanks a lot!
