### ISSUE TITLE
I hope that when element's contentEditable is false, don't popup selection.

### ISSUE THREAD

**Issue by wiky** [wysiwygjs/wysiwyg.js#30]
I hope that when element's contentEditable is false, don't popup selection.
so I add code in `wysiwyg-editor.js`, line 613, like this:
```js
    ....
        },
    onSelection: function( collapsed, rect, nodes, rightclick )
        {
            // I hope that when element's contentEditable is false, don't popup selection.
            if (wysiwygeditor.getElement().contentEditable === 'false') {
                return;
            }
            var show_popup = true,
                $special_popup = null;
    ....
```
 [see code insert point](https://github.com/wysiwygjs/wysiwyg.js/blob/d9946194acffee87acecca45508b60d241a41e83/src/wysiwyg-editor.js#LC613)

After do that, I can set element `contentEditable="false"`, and make the element unEditable completely.

Hope  to accept my advice. Thx~

**Comment by wysiwygjs** [comment]
Bad hack.
We can add a "$('#container').wysiwyg('disabled');" feature if you need this.

**Comment by Nyalab** [comment]
agree, i have seen a few wysiwyg these times, and the common pattern is making something like
```js
const editor = wysiwyg({
  readOnly: true,
})
```

**Comment by wiky** [comment]
@wysiwygjs If you can provide a `disabled ` method/way should be great. I think it's necessary. hope soon.

The starting point of my method is linkage with UI, and simplest.

**Comment by wiky** [comment]
I saw U add a `readonly` method, it's amazing, and it's what I need, Thx~

**Comment by Nyalab** [comment]
ok, nice feature!
