### ISSUE TITLE
[git] Could you specify correctly your account?

### ISSUE THREAD

**Issue by kud** [wysiwygjs/wysiwyg.js#31]
![screenshot 2015-05-19 at 15 27 31](https://cloud.githubusercontent.com/assets/655838/7703977/ccb7c90a-fe3b-11e4-97b9-2235ab021a4e.png)

https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity

**Comment by dandv** [comment]
Yeah, :+1:

**Comment by kud** [comment]
Lovely ;)
