### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by dandv** [wysiwygjs/wysiwyg.js#33]
A very handy feature, that would make this minimalistic editor perfect!

I'm [comparing WYSIWYG editors](https://github.com/dandv/comparisons/blob/master/JavaScript-WYSIWYG-editors.md) and have been looking for this feature.

**Comment by axd** [comment]
Is working for me already.

**Comment by dandv** [comment]
Does work at http://wysiwygjs.github.io/ if you copy an image from another browser tab and paste it in the demo.

But it doesn't paste an image from the system clipboard (Windows). For example, open an image locally in an image viewer, copy it, and paste it in the demo.
