### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by alexcroox** [wysiwygjs/wysiwyg.js#37]
Running with jQuery (using _jQuery instead of $ in no conflict mode if that makes a difference).

It creates the start of the markup including the container div `wysiwyg-container` but then the error fires:

`Uncaught TypeError: Cannot read property 'length' of undefined`

```
m.extend.each @ app.js?1434763527:2
a @ app.js?1434763527:7504
(anonymous function) @ app.js?1434763527:7504
m.extend.each @ app.js?1434763527:2
m.fn.m.each @ app.js?1434763527:2
n.fn.wysiwyg @ app.js?1434763527:7504
playerInteractionController.setupDefaultClickHandlers @ app.js?1434763527:9971
(anonymous function) @ app.js?1434763527:9476
m.Callbacks.j @ app.js?1434763527:2
m.Callbacks.k.fireWith @ app.js?1434763527:2
m.extend.ready @ app.js?1434763527:2
J @ app.js?1434763527:2
```

Called with `_jQuery('.wysiwyg').wysiwyg();`

**Comment by wysiwygjs** [comment]
What is `this` in `fn.wysiwyg()`?
https://github.com/wysiwygjs/wysiwyg.js/blob/master/src/wysiwyg-editor.js#L807

**Comment by alexcroox** [comment]
It's a jQuery selector of the textarea I am targeting

`[textarea#build-modpack-text.wysiwyg, prevObject: m.fn.init[1], context: document, selector: ".wysiwyg"]`

**Comment by pehlert** [comment]
Same problem here, except that I'm using the regular short jQuery object ($).
The issue occurs in wysiwyg-editor.js:746 where toolbar_buttons is undefined for me.

**Comment by wysiwygjs** [comment]
The demo works?
Could you provide me a testcase?

**Comment by pehlert** [comment]
Sorry, it only happens when the buttons option is not defined. I just checked out the demo on your website and realised that I forgot to define all these button functions. I did a plain $('.wysiwyg').wysiwyg();
Maybe this should still print a warning or initialize with an empty toolbar at least?

**Comment by wysiwygjs** [comment]
You are right.
The problem is, that the code is agnostic to languages and buttons (you may use jpeg/png/gif/svg images, "font-face" buttons, ...).
Maybe the best is an empty toolbar.

**Comment by pehlert** [comment]
Great! Thank you and keep up the good work!
