### ISSUE TITLE
TypeError if Enter pressed in popup

### ISSUE THREAD

**Issue by RobertAudi** [wysiwygjs/wysiwyg.js#4]
![wysiwyg-js-type-error](https://cloud.githubusercontent.com/assets/87562/6168043/b3e85568-b2c1-11e4-8a22-603c3a961810.png)

Steps to reproduce:

1. Click on the "Insert Link" button
2. Type something in the text input
3. Press Enter

Tested on Chrome and Safari. Seems to work in Firefox.

**Comment by wysiwygjs** [comment]
Fixed by f8274a1497
