### ISSUE TITLE
Unable to resize image in Google Chrome.

### ISSUE THREAD

**Issue by neizod** [wysiwygjs/wysiwyg.js#41]
Using Google Chrome 43, I can't resize image, while Firefox can do this.

Is this bug in Google Chrome, or Firefox just smarter about handling image?

**Comment by trecreat** [comment]
IE can resize image this too ?!!! 
![screen](https://cloud.githubusercontent.com/assets/7949001/9267562/6e7998ee-427b-11e5-9b44-f8ce25c0a4d0.png)

**Comment by deepnees** [comment]
Same here. Edge, Ie, Firefox works. But Chrome has issue.
