### ISSUE TITLE
Click on anchor in the wysiwyg editor will create error

### ISSUE THREAD

**Issue by AnthonyTsang** [wysiwygjs/wysiwyg.js#43]
Testing code
```
editor.wysiwyg();

setTimeout(function(){
  editor.wysiwyg('shell').insertHTML('<a href="http://google.com">google</a>');
}, 200);
```

After running the code, an anchor will be added to the editor. When click on the anchor this error is shown.
```
Uncaught TypeError: Cannot read property 'title' of undefined
toolbar_button	@	wysiwyg-editor.js:426
content_insertlink	@	wysiwyg-editor.js:74
(anonymous function)	@	wysiwyg-editor.js:620
v.extend.each	@	jquery.min.js:2
option.onSelection	@	wysiwyg-editor.js:618
handleSelection	@	wysiwyg.js:930
(anonymous function)	@	wysiwyg.js:33
```

And nothing happened. 
What I think, it should open a new tab to show the anchor page.

**Comment by AnthonyTsang** [comment]
My workaround is to stop using `wysiwyg-editor.js` and handle the anchor click by myself, including open new tab.

**Comment by wysiwygjs** [comment]
Can't reproduce. Do you set an attribute id=name to the editor and a link inside the editor should scroll to the editor?
I hate workarounds - this issue should be easy to fix.

**Comment by AnthonyTsang** [comment]
Bold, italic, underline and other controls are working perfectly. Only anchor failed in this case. 
BTW `insertLink` only allow to pass the url, so I use `insertHTML`.

A bit more context, I am using backbone and underscore template. 
I will do more testing later today.

**Comment by wysiwygjs** [comment]
Could you provide me a testcase?

**Comment by ericsantanna** [comment]
I'm facing the same problem.

JSFiddle:
http://jsfiddle.net/nrzy1gqy/1/

I think I can't fix this without messing up the code...

**Comment by wysiwygjs** [comment]
Fixed.
You will not see a submit-button if you don't configure "submit:{...}"
