### ISSUE TITLE
demo example question

### ISSUE THREAD

**Issue by zfan40** [wysiwygjs/wysiwyg.js#48]
header: index != 1 ? false 

in the demo, i see this, not sure if this is intentionally done to hide this customised function. same to fontsize

**Comment by wollmers** [comment]
I also struggled with this. It turns on or off e.g. the font selection specifically for edit areas. If you have only one edit area or want the same features for areas then you can remove the condition like this:

    fontname: index == 1 ? false : {  // from example

    fontname:  {  // removed condition
