### ISSUE TITLE
expose getSelectedNodes or add onSelection event to editor onInput and onBlur

### ISSUE THREAD

**Issue by souporserious** [wysiwygjs/wysiwyg.js#49]
First off, awesome abstraction for a WYSIWYG editor. Building a React plugin with this and wondering if you'd be willing to expose the `getSelectedNodes` method? Or adding the `onSelection` event to `onInput` and `onBlur` so I can determine what new nodes are in place when toggling different formats. Want to build highlighting in the toolbar for whatever is currently selected.

**Comment by wysiwygjs** [comment]
Highlighting the toolbar is a good point.

"onInput" should fire "onSelection()":
addEvent( node_wysiwyg, 'input', debounced_changeHandler );

If you need onBlur - we can certainly add that.

**Comment by souporserious** [comment]
Awesome. I'll look into why `onInput` isn't firing. So for instance if I bold some text I won't get an `onSelection` fire. Would need this to determine how what needs to be highlighted in the toolbar. What about exposing `getSelectedNodes`? I feel that would be useful to be able to determine what nodes are currently selected and do whatever with them. Thanks for the quick response!
