### ISSUE TITLE
stopPropagation doesn't work!

### ISSUE THREAD

**Issue by medBouzid** [wysiwygjs/wysiwyg.js#61]
for some reason I added e.stopPropagation() for mouseup to a wysiwyg_node 

    $ ("#editor0").on("mouseup", function(e){ e.stopPropagation(); });

but even with that the mouseup event still triggered !! what's the problem here ?

**Comment by wysiwygjs** [comment]
Does this work?
$('#editor0 .wysiwyg-editor').mouseup(...)

**Comment by medBouzid** [comment]
No it doesn't !! I see that you create a new copy of the original textarea and you apply the wysiwyg on it !
if you go to the page of examples you have the first textarea with ID = editor1, and that textarea becomes a div with CLASS = wysiwyg-editor
So even if I apply $(' .wysiwyg-editor').mouseup(...) or  $(' .wysiwyg-editor').on("mouseup", ...) it doesn't work.
If you can just explain me the reason in the source code I can figure out how to deal with it. Thanks.

**Comment by medBouzid** [comment]
it was an error from me, sorry about that. Thank you!
