### ISSUE TITLE
get wysiwyg instance of dom element

### ISSUE THREAD

**Issue by CanRau** [wysiwygjs/wysiwyg.js#63]
Is it somehow possible to get the wysiwyg instance of an contenteditable dom element?
kinda like the reverse of getElement()

I'm using raw wysiwyg.js and am trying to build a custom toolbar.
It's applying toolbar to any element with given class and turns it into wysiwyg. But I'm not sure on how to apply click handlers the best way.

Thought of a "global" click event checking which editor it should apply changes, but I'm not getting the actual plugin instance when providing the nearest contenteditable.

Would be quite handy :)

PS: vanilla toolbar would be great to have, too. I think there more and more people switching to plain/vanilla js these days..

**Comment by wysiwygjs** [comment]
`getElement()` should return the contenteditable dom element (the name is a bit crapy - but I don't want to break the AP).

**Comment by CanRau** [comment]
Aha, no..I mean reverse. Like I get a DOM element e.g. textarea and from this I would love to get the instance of wysiwyg like textarea.getAttribute('wyswig-instance') or something like that

Maybe this helps a little understanding http://stackoverflow.com/questions/29222027/vanilla-alternative-to-jquery-data-function-any-native-javascript-alternati

**Comment by lukeed** [comment]
@wysiwygjs: @CanRau is talking about a DOM accessor, which is a traditional jQuery-plugin feature.

For example:

```js
var $el = $('#item');
var el = document.getElementById('item');

$el.getEditor(); //=> WYSIWYG <Object>
el.getEditor() //=> WYSIWYG <Object>
```

@CanRau: For the time being, you might just want to nest the instance directly into your element:

```js
var el = document.getElementById('item');
el.editor = wysiwyg({...});

el.editor; //=> Wysiwy.js <Object>
```

**Comment by CanRau** [comment]
Exactly @lukeed !
Thanks, good idea, but actually I switched to CKEditor for now for various reasons...keeping an eye on wysiwyg.js
