### ISSUE TITLE
can't resize of images?

### ISSUE THREAD

**Issue by rowthan** [wysiwygjs/wysiwyg.js#64]
when it work as a local html, when we add a image and then we can do something for the picture,such as resize of it and move it. but when it work in webserver, it does not work! why ? not only mine but also your site --http://wysiwygjs.github.io/   I can not adjust the images!!

**Comment by rowthan** [comment]
and can not copy paste img,,,,,

**Comment by zizoupro** [comment]
hey @rowthan  can you help me configure the image upload function? i dont understand how :/
