### ISSUE TITLE
Feature request - Target missing when use Insert link

### ISSUE THREAD

**Issue by AkoeGit** [wysiwygjs/wysiwyg.js#66]
Is it possible to "Insert link" and give a _target_ because sometimes I want to open a link in a new browser and sometimes I want to refer to a page on the current website.

![image](https://cloud.githubusercontent.com/assets/15892381/15421411/63925a9a-1e73-11e6-93d1-427df7bd60a3.png)

**Comment by Giovancruz** [comment]
+1
