### ISSUE TITLE
When preloading textarea with html, entities like &lt are getting translated into html

### ISSUE THREAD

**Issue by kahuna76** [wysiwygjs/wysiwyg.js#68]
So I am prefilling a textarea with content previously captured through the wysiwyg editor. <> tags are replaced with html entities &lt; & &gt; but when I now initialise wysiwyg on this content again it translates it back to <> causing the html to get executed. Am I making sense ? Just an example:

Input the below in wysiwygjs editor:

`<img src='https://placekitten.com/200/300' onload='alert(8)'>`

When saved it will look like this (which is OK because I dont want it to get interpreted)

`&lt;img src='https://placekitten.com/200/300' onload='alert(8)'&gt;`

now make a textarea with this content and initialise the editor on it 

`<textarea>&lt;img src='https://placekitten.com/200/300' onload='alert(8)'&gt;</textarea>`

what happens ? You'll get 8 alerted ....

I notice that if I insert that same saved content with the .setHtml() function it fills it in correctly unrendered but this is not practical for large pieces of content with line breaks etc

Any ideas how to get around this ?

**Comment by wysiwygjs** [comment]
You are right.
'&lt;img onalert="..."&gt;' triggers when the image is finally loaded.
This is perfectly fine from the browser perspective.
Maybe we should add a workaround.

**Comment by kahuna76** [comment]
But why does it not render it as just '<' as it should with &lt; but instead it sees it as a real tag

I mean it's no big deal as I can just json_encode the PHP variable and set it with setHtml() but would be nice to have a workaround

**Comment by wysiwygjs** [comment]
Try the flicker-free markup:
````
<div class="wysiwyg-container">
 <div class="wysiwyg-wrapper">
  <div class="wysiwyg-placeholder">placeholder...</div>
  <div class="wysiwyg-editor" contenteditable="true"><!-- PLACE YOUR HTML HERE --></div>
  <textarea style="display:none;" name="editor"></textarea>
 </div>
</div>  
````

But it will also trigger the img-onload...

**Comment by kahuna76** [comment]
Oh sweet - I was trying to figure ut how to get rid of that flicker too :)

**Comment by kahuna76** [comment]
I tried the flicker-free markup but I end up with 2 textareas on top of each other ?
![https___172_16_143_130_roel](https://cloud.githubusercontent.com/assets/7201876/19175466/9302622a-8c82-11e6-96e0-43455b965085.jpg)
