### ISSUE TITLE
Font sizes in em

### ISSUE THREAD

**Issue by swist666** [wysiwygjs/wysiwyg.js#7]
< font size="x" > is not very good way to format font size. Maybe better would be even < span style="font-size:1em" >. You know how to change this behaviour? I know it's hard to do this with execCommand.

**Comment by wysiwygjs** [comment]
We did consider a "wysiwyg.css()" function - but it is a bit tricky. You have to iterate the selection and apply the style to all the textnodes.

**Comment by wysiwygjs** [comment]
Updated demo
