### ISSUE TITLE
Latest code not in NPM

### ISSUE THREAD

**Issue by bilbosan** [wysiwygjs/wysiwyg.js#71]
hey there,

I'm encountering the bug in https://github.com/wysiwygjs/wysiwyg.js/issues/43, which you fixed in https://github.com/wysiwygjs/wysiwyg.js/commit/45af317b4cf78aeac1c9b16eb3a836cb11d1c4bf.

However, that commit isn't in the code that's in the NPM repo. I'm hoping you can push the latest code to NPM so that I can pull from there?

**Comment by wysiwygjs** [comment]
@Nyalab has the password, see:
https://github.com/wysiwygjs/wysiwyg.js/issues/24

**Comment by Nyalab** [comment]
Hello everyone, sorry, i was busy, i released 2.0.0 on npm right now, tell me if all is ok for all of you ;)
