### ISSUE TITLE
Enabling H1-H6 tags

### ISSUE THREAD

**Issue by ddibiase** [wysiwygjs/wysiwyg.js#74]
Hello,

I'm using the raw API and have a need to enable H1-H6. I can see the demo has an example but seems to be jQuery focused. I was wondering if there's an example or a method for the raw library that works well.

Also I'm wondering how to generally hook and enable other tags within the library.

Thanks.

**Comment by alrykov** [comment]
@ddibiase , looks like you could use
```javascript
wysiwygeditor.format('h1');
```
