### ISSUE TITLE
How to make the textarea height fit the parent div height?

### ISSUE THREAD

**Issue by carlos-carneiro** [wysiwygjs/wysiwyg.js#76]
I would like to make the textarea/editor height equal the parent div height. See the image below:

![screenshot-2018-1-4 wysiwyg 1](https://user-images.githubusercontent.com/10589421/34578624-cf43feec-f16c-11e7-999a-0127c54e49ed.png)

**Comment by wysiwygjs** [comment]
````
.wysiwyg-container textarea {
    min-height: 5em;
}
````

**Comment by MonsterTan** [comment]
+1

**Comment by carlos-carneiro** [comment]
It does not work : -( 

I put this like the image below:
![code](https://user-images.githubusercontent.com/10589421/34691684-8c7103e0-f4a4-11e7-9440-0e4ab6c8fe3b.png)

I can change manually the line surrounded of green in hit and miss but it's not good. And if I change it to 100% its height outstrip the parent div height.

**Comment by wysiwygjs** [comment]
You may want to use "flexbox"

**Comment by wysiwygjs** [comment]
Or you set css-height to 100% (and set box-sizing to 'border-box')

**Comment by carlos-carneiro** [comment]
I put the height manually in vw UM. Thanks I'm going to close this issue now.
