### ISSUE TITLE
Issue with lists insertion and tabulation

### ISSUE THREAD

**Issue by webandbusiness** [wysiwygjs/wysiwyg.js#81]
Hello, i tried to add on tool bar 
ordered and unordered list  with 
`insertorderedlist: function()
 {
                execCommand( 'insertorderedlist');
                callUpdates( true ); //
                return this;
            }
`  in source code

But due to css (i think) it doesnt appear
How to extends tools bars
Kind regards

**Comment by wysiwygjs** [comment]
Reload the demo
