### ISSUE TITLE
How to gather Attached files

### ISSUE THREAD

**Issue by webandbusiness** [wysiwygjs/wysiwyg.js#82]
I am using wysiwyg for blog project, to post articles,
I need to gather attached files on submit.

the browser fonction call back indeed make the file available, but most of the time, buttons definitions and handlers is common for all projet.

I suggest to add a node_container object in commands object returned by  wysiwyg(....), so that one can append input files there or do any general handling for specific nodes
Regards.

**Comment by wysiwygjs** [comment]
Maybe I missed the point.
You want to add `<input type="file">` to your `<form>`?
If so, such a function is not related to the editor.

**Comment by webandbusiness** [comment]
Thanks for your reply...
The point is: How  can i access and upload toward a server attached files from the editor.

The issue is, in buttons definitions the browser function  append files, <input type="file"> without name field, when using formData() they are not available
How to do
Regards

**Comment by webandbusiness** [comment]
I suggest to randomly name attached files, 
and modify the core code as follow, what you think?

```
commands = {
            // properties
            sync: function()
            {
                // sync textarea immediately
                if( syncTextarea )
                    syncTextarea();
                return this;
            },
          // more commands functions....
			
		  // then i just add the editor node container, to make it available for any purpose
			node: node_container
        };

```

Then in user code he can parse or iterate the node container to access attached files
Regards

**Comment by wysiwygjs** [comment]
Like this?
1. Someone clicks "Insert image"
2. The picture is uploaded to the server
3. The url of uploaded image is inserted

**Comment by webandbusiness** [comment]
I am talking about files
attached files not dataurl inline  insertion
attached files cliped, files like .pdf, .docx, .txt etc......

**Comment by wysiwygjs** [comment]
This feature should be there (test the clip icon):
https://github.com/wysiwygjs/wysiwyg.js/blob/master/index.html#L78

You get the reference to an `<input file>`, your application has to decide what to do.
