### ISSUE TITLE
Add Youtube video

### ISSUE THREAD

**Issue by ORLAND0** [wysiwygjs/wysiwyg.js#9]
Hello, Incase anyone would like to use it, i made a button to add a youtube iFrame.

	var $wysielem=$(element);
	var wysiwygeditor = $(element).wysiwyg({
		buttons: {				
			insertYT: {
				popup: function( $popup, $button ) {                           
					var placeholder_url="youtube.com/watch?v=...";
					var $inputurl = $('<input type="text" value=""' + (placeholder_url ? ' placeholder="'+placeholder_url+'"' : '') + ' />').addClass('wysiwyg-input')
					var submitUrl= function(){
						var iframeHTML=getTYIframe($inputurl.val());
						if(iframeHTML==0){alert('Entry is not a youtube video URL'); return 0;}
						else{$wysielem.wysiwyg('shell').insertHTML(getTYIframe($inputurl.val())); return 1;}
					};
					$inputurl.keypress(function(event){
							if( event.which != 10 && event.which != 13 )
								return ;
							// Catch 'NS_ERROR_FAILURE' on Firefox 34
							try {
								submitUrl();
								$wysielem.wysiwyg('shell').closePopup();	
							}
							catch( e ) {$wysielem.wysiwyg('shell').closePopup();}
					});
					var $okaybutton = $('<a href="#" title="Submit"></a>').click(function(event){
						if( $inputurl.val() )
						{submitUrl();$wysielem.wysiwyg('shell').closePopup();}
						else $wysielem.wysiwyg('shell').closePopup();
						event.stopPropagation();
						event.preventDefault();
						return false;
					});
					var $content = $('<div/>').addClass('wysiwyg-toolbar-form').attr('unselectable','on');

					
					$content.append( $inputurl ).append($okaybutton);
					$popup.append($content);
				},
				title: 'Insert Video',
				image: 'Video',
			},
		},
	});

		
		function getYTID(url) {
			var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
			var match = url.match(regExp);

			if (match && match[2].length == 11) {
				return match[2];
			} else {
				return 0;
			}
		}
		function getTYIframe(url){
			myId=getYTID(url); if(myId==0)return 0;
			return '<iframe width="560" height="315" src="//www.youtube.com/embed/' 
			+ myId + '" frameborder="0" allowfullscreen></iframe>';
		}

**Comment by seymores** [comment]
Thanks!

**Comment by ORLAND0** [comment]
funny timing! i didnt even see your issue from the day before... glad my first github post went to good use :)

**Comment by wysiwygjs** [comment]
Fixed. There is a callback "videoFromUrl(url)" to create the embed code from the URL.
